Workaround CI adm generation failing on impish
ibus can’t be setup in the container, let’s ignore install failure.
We will review the PR anyway if anything is generated and it not
expected.

diff --git a/.github/workflows/adm-builds.yaml b/.github/workflows/adm-builds.yaml
--- a/.github/workflows/adm-builds.yaml
+++ b/.github/workflows/adm-builds.yaml
@@ -99,7 +99,8 @@ jobs:
         run: |
           export DEBIAN_FRONTEND=noninteractive
           apt update
-          apt -y install ubuntu-desktop
+          # Ignore installation error, we will remove the PR anyway if anything is missing
+          apt -y install ubuntu-desktop || true
       - name: Collect support keys
         run: |
           chmod 755 ./admxgen
