Move quality scripts inside github workflow

diff --git a/.github/workflows/qa.yaml b/.github/workflows/qa.yaml
--- a/.github/workflows/qa.yaml
+++ b/.github/workflows/qa.yaml
@@ -54,7 +54,12 @@ jobs:
           set -eu
 
           go mod tidy
-          ./.github/ci/check-modules
+          MODIFIED=`git status --porcelain go.sum go.mod`
+          if [ -n "$MODIFIED" ]; then
+              echo "ERROR: go module files aren't up to date:"
+              git --no-pager diff go.mod go.sum
+              exit 1
+          fi
         if: ${{ always() }}
       - name: Building
         run: go build ./...
@@ -122,4 +127,33 @@ jobs:
           go install google.golang.org/protobuf/cmd/protoc-gen-go \
             google.golang.org/grpc/cmd/protoc-gen-go-grpc
       - name: Check generated files
-        run: ./.github/ci/check-generate
+        run: |
+          set -eu
+
+          # Ignore mod file changes; README.md and po files
+          # Modules are handled in another check and aren't related to generator
+          # po and README.md files will be automatically updated once master in master.
+          git update-index --assume-unchanged go.* po/* README.md
+          on_exit() {
+              # Restore files
+              git update-index --no-assume-unchanged go.* po/* README.md
+          }
+          trap on_exit EXIT INT QUIT ABRT PIPE TERM
+
+          go generate ./...
+
+          # Handle everything but po and assets files
+          modified_files=`git status --porcelain --untracked-files=no`
+
+          # Check generated files
+          MODIFIED=""
+          if [ -n "$modified_files" ]; then
+              # Ignore assets modification time and protoc version.
+              MODIFIED=`git difftool -y -x "diff -I 'modTime' -I '^//.*protoc.*v'"`
+          fi
+
+          if [ -n "$MODIFIED" ]; then
+              echo "ERROR: 'go generate' modified files:"
+              git --no-pager diff
+              exit 1
+          fi
